# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa5ddeb2bf00db98848adc28ce8644e6dda1885edaa9635c40582b225b77692d657e8e06de66a045fa99d46d7305c7302783c71f7b68d484cdacb4238ecdac06

test:
  secret_key_base: b8a7be9328877ebf45d14ec2c9e1d5f2b934e278fb8c13ca8d1e7f93bca2b3a5c27ca32e98abf6c16ce487f063afef18ba45090b75bc355952d79085b9366cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
